name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:

  Docker:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 16
        
    - name: Setup git config
      run: |
        git config user.name "GitHubActions Bot"
        git config user.email "<>"
        
    - name: Dependencies
      run: npm ci
      
    - name: Build
      run: npm run build
      
    - name: Save version
      id: version
      run: echo ::set-output name=tag::$(echo $(node -p -e "require('./package.json').version"))
      
    - name: Increase version
      run: npm version patch
      
    - name: Push new version
      run: git push
      
    - name: Login to DockerHub Registry
      run: echo ${{ secrets.WEBEDITOR_DOCKERHUB_PASSWORD }} | docker login -u ${{ secrets.WEBEDITOR_DOCKERHUB_USERNAME }} --password-stdin
      
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag paulowillers/webeditortest:${{ steps.version.outputs.tag }}
      
    - name: Push to DockerHub
      run: docker push paulowillers/webeditortest:${{ steps.version.outputs.tag }}
